name: "RED: Test PyPI Upload Job"

on:
  workflow_dispatch:
  push:
    branches:
      - "test"
    tags:
      - "all"
      - "pypi"
      - "pypi-r"

jobs:

  build_python:
    runs-on: ubuntu-latest
    name: Build Python
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install Tooling
        run: |
          pip install --upgrade pip
          pip install tox==3.28

      # Emulate Build Python
      - name: Build Python in './dist/' folder
        run: tox -e build

      # Emulate Artifacts Upload
      - run: echo ARTIFACTS=unit_test_artifacts >> $GITHUB_OUTPUT
        id: set_artifacts_ref

      - name: Archive Python
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.set_artifacts_ref.outputs.ARTIFACTS }}
          path: dist
    outputs:
      ARTIFACTS: ${{ steps.set_artifacts_ref.outputs.ARTIFACTS }}

  call_pypi1:
    name: 'EXPECT FAIL: allow_existing is set to false'
    needs: build_python
    uses: boromir674/automated-workflows/.github/workflows/pypi_env.yml@test
    with:
      distro_name: cicd_test_workflow
      distro_version: "0.0.1"
      should_trigger: true
      pypi_env: "PYPI_TEST"
      artifacts_path: ${{ needs.build_python.outputs.ARTIFACTS }}
      require_wheel: true
      allow_existing: false
    secrets:
      TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
