name: "GREEN: Test Static Code Analysis Workflow"

### Static Code Analysis (sca) ###

# To Trigger:

# export tt='v-sca-g-1.0.0'
# git tag -d "$tt"; git push --delete origin "$tt"; git tag "$tt" && git push origin "$tt"

on:
  workflow_dispatch:
  push:
    branches:
      - "test"
    tags:
      - "all"
      - "sca"
      - "sca-g"
      - "v-sca-g*"

jobs:

  call_static_code_analysis:
    name: Call Static Code Analysis
    needs: emulate_target_source_changes
    if: always()
    uses: boromir674/automated-workflows/.github/workflows/lint.yml@test
    with:
      dedicated_branches: "sqa_test_temp"
