name: "GREEN: Test Static Code Analysis Workflow"

### Static Code Analysis (sca) ###

# To Trigger:
# export tt='sca-g'
# git tag -d "$tt"; git push --delete origin "$tt"; git tag "$tt" && git push origin "$tt"

on:
  workflow_dispatch:
  push:
    branches:
      - "test"
    tags:
      - "all"
      - "sca"
      - "sca-g"

jobs:

  emulate_running_on_main:
    runs-on: ubuntu-latest
    name: Build Python
    steps:
      - uses: actions/checkout@v4
      - run: ${{ 'main' == github.ref_name }} == 'true' || exit 1

  call_static_code_analysis:
    name: Call Static Code Analysis
    needs: emulate_running_on_main
    if: always()
    uses: boromir674/automated-workflows/.github/workflows/lint.yml@test
