name: Test CI/CD Pipeline

on:
  push:
    branches:
      - "*"
    tags:
      - v*


jobs:

    mock_succeeded_ci_test_job:
      runs-on: ubuntu-latest
      steps:
        - run: echo "Mock CI Test Job"


# Use Wowrkflow from public repository
# {owner}/{repo}/.github/workflows/{filename}@{ref}

    # call-workflow-1-in-local-repo:
    #   uses: octo-org/this-repo/.github/workflows/workflow-1.yml@172239021f7ba04fe7327647b213799853a9eb89
    # call-workflow-2-in-local-repo:
    #   uses: ./.github/workflows/workflow-2.yml


  # TEST Case 1 - CI Passes
    call_docker_job_after_ci_pass:
      name: Trigger Docker Workflow
      needs: mock_succeeded_ci_test_job
      uses: boromir674/automated-workflows/.github/workflows/workflow.yml@main
      with:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        acceptance_policy: 3
        image_slug: "cicd-test"
        image_tag: "latest"
      secrets:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      # secrets: inherit

    verify_docker_image_pushed:
      runs-on: ubuntu-latest
      needs: call_docker_job_after_ci_pass
      steps:
        - run: echo ${{ needs.call_docker_jon.outputs.IMAGE_REF }}
        - run: echo "IMAGE_REF=${{ needs.call_docker_jon.outputs.IMAGE_REF }}" >> $GITHUB_ENV
        - name: Retrieve Layers of ${{ needs.call_docker_jon.outputs.IMAGE_REF }}
          run: |
            docker manifest inspect "$IMAGE_REF" > docker_layers.json
            command_exit_status=$?
            if [ $command_exit_status -eq 0 ]; then
              echo "PASS: Verify Docker Image "${IMAGE_REF}" was Pushed to DockerHub"
            else
              echo "FAIL: Verify Docker Image "${IMAGE_REF}" was Pushed to DockerHub"
              exit 1
            fi

  # # TEST Case 2 - CI Fails

  #   call_docker_job_after_ci_fail:
  #     uses: boromir674/automated-workflows/.github/workflows/workflow.yml@main
  #     name: Trigger Docker Workflow
  #     with:
  #       DOCKER_USER: ${{ secrets.DOCKER_USER }}
  #       image_slug: "cicd-test"
  #       image_tag: "latest"
  #     secrets:
  #       DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}



  # # TEST Case 2 - CI Skipped

  #   call_docker_job_after_ci_skip:
  #     uses: boromir674/automated-workflows/.github/workflows/workflow.yml@main
  #     name: Trigger Docker Workflow
  #     with:
  #       DOCKER_USER: ${{ secrets.DOCKER_USER }}
  #       image_slug: "cicd-test"
  #       image_tag: "latest"
  #     secrets:
  #       DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}